# Generated by Django 5.2.7 on 2025-10-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to='skills/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
